# https://k3d.io/v5.4.1/usage/configfile/
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: hands-on
servers: 1
agents: 3
ports:
  - port: 9080:80
    nodeFilters:
      - loadbalancer
  - port: 9443:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-hands-on
    hostPort: "5000"
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --cluster-domain=labs.handson.local
        nodeFilters:
          - server:*
      - arg: --node-taint=node-role.kubernetes.io/master=:NoSchedule
        nodeFilters:
          - server:*
  runtime:
    serversMemory: 1G
    agentsMemory: 1G
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true