apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
helmCharts:
- name: prometheus 
  releaseName: prometheus
  version: 15.13.0
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml