apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
helmCharts:
- name: vault
  releaseName: vault
  version: v0.22.0
  repo: https://helm.releases.hashicorp.com
  includeCRDs: true
  valuesFile: values.yaml