apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml

helmCharts:
- name: grafana 
  releaseName: grafana
  version: 6.38.7
  repo: https://grafana.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml
  valuesInline: 
    fullnameOverride: grafana