apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: echo
  namespace: default
spec:
  encryptedData:
    echo: AgCPE2Lxy8k/aV2npim6gfUqcSM0+A2xEnV4Uzb9wAIk8/Dps+jEuYAaxGzLWz0J8oVi1/G+tuAlRBi6lXLxWPapkr0UrR6PJfCdmj3K1iYzeVX2xPNFGKTIr0YOOq19CdnXb0WDI8dJqe2c0+UKueUWYbcdC1EmAbVo87k9nK0ywYb2OBfGPeeyGFqXQicokrMADBOLZlRkQmRAwlcB0ebSRhk7GVCErWZuwPqfhJJEOXQmelcWjtUgIYvwU2OeFMhtoCADCbrUE5NlIThYFJfBqgwAd2FsGgGYE6ld2OC0z/PZZ+lL+7dT/RlQfppgqLWvCmabvGD0xO8OoMS7xIriH6+ob9/SKN1tHvJ0VzucthsqKdknEQAN9GqVSiCZKIuKW7VOTNHNMEC/tlnYDCYb2Qj1Q/W+Oy8IikNU8rOvq9CkLvqtgJBD1rFJ0/H2hnMRA21E5bXerJhC9fO5/E8Fl7p05HL3Lq1oBiXMWk47Y/KSJzs0Y8T0WBZ8Nse3NJctuZz4rL7aY/iiBpRyWJOuGoklEnt8or/Kxc+eJp5GSEU+2DwhH4OS0o8CaB8kv/3g4VmA+muGFnJvpSJal3Qbd1ap1xQBCe6P6BBg8E6531hYW/gk1ry41rw1H6EX37LV2ZI8oubQ2WB9+Wsc7wOJsHaMJBnbfI3wGPIOFG3K6QygV0IDB7ATAgegBMH3KEZCOH2qSnLc0xJDcA==
  template:
    metadata:
      creationTimestamp: null
      name: echo
      namespace: default

