apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-helm
  labels:
    helm.sh/chart: helm-0.1.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: ""
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            helm.sh/chart: helm-0.1.0
            app.kubernetes.io/name: helm
            app.kubernetes.io/instance: nginx
            app.kubernetes.io/version: "1.16.0"
            app.kubernetes.io/managed-by: Helm
        spec:
          imagePullSecrets:
            - name: nexus-auth
          serviceAccountName: default
          securityContext:
            {}
          containers:
          - name: helm
            securityContext:
              {}
            imagePullPolicy: Always
            image: "__IMAGE-REPOSITORY__:latest"     
            ports:
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 150m
                memory: 128Mi
            livenessProbe:
              null
            readinessProbe:
              null
            envFrom:
            - secretRef:
                name: nginx-helm-secrets
            env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          restartPolicy:  Never
          nodeSelector:
            agentpool: AKS-Exemplo

