apiVersion: v1
kind: Service
metadata:
  name: nginx-helm-service
  labels:
    helm.sh/chart: helm-0.1.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  selector:
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: nginx